highlighter: rouge
markdown: kramdown

title:            Felix Fu
aboutme:          My name is Felix Fu.
url:              http://blackswanblood.github.io/

author:
  name:           Felix Fu
  email:          yuxiang.f@alumni.ubc.ca        
  github:         https://github.com/blackswanblood

paginate:         10
