highlighter: pygments
markdown: redcarpet

title:            Felix Fu
aboutme:          A person.
url:              http://blackswanblood.github.io/

author:
  name:           Felix Fu
  twitter:        
  github:         https://github.com/blackswanblood

paginate:         10
