highlighter: rouge
markdown: kramdown

title:            Felix Fu
aboutme:          My name is Assil Ksiksi. I write low-level software at Cisco.
url:              http://blackswanblood.github.io/

author:
  name:           Felix Fu
  twitter:        
  github:         https://github.com/blackswanblood

paginate:         10
